export const images = [
  {
    id: 1,
    lqip: "/images/lqip/andre-lqip.jpg",
    src: "/images/andre.png",
    alt: "andre",
    href: "https://www.instagram.com/dre_yonce/",
    name: "andre",
  },
  {
    id: 2,
    lqip: "/images/lqip/adrienne-lqip.jpg",
    src: "/images/adrienne.png",
    alt: "adrienne",
    href: "https://www.instagram.com/adrienney/",
    name: "adrienne",
  },
  {
    id: 3,
    lqip: "/images/lqip/alex-lqip.jpg",
    src: "/images/alex.png",
    alt: "alex",
    href: "https://www.instagram.com/meowchow/",
    name: "alex",
  },
  {
    id: 4,
    lqip: "/images/lqip/kyoung-lqip.jpg",
    src: "/images/kyoung.png",
    alt: "kyoung",
    href: "https://www.instagram.com/k_young32/",
    name: "kyoung",
  },
  {
    id: 5,
    lqip: "/images/lqip/phil-lqip.jpg",
    src: "/images/phil.png",
    alt: "phil",
    href: "https://www.instagram.com/phillybonbilly/",
    name: "phil",
  },
  {
    id: 6,
    lqip: "/images/lqip/tran-lqip.jpg",
    src: "/images/tran.png",
    alt: "tran",
    href: "https://www.instagram.com/trantnguyen?igsh=MWQ1ZGUxMzBkMA==",
    name: "tran",
  },
  {
    id: 7,
    lqip: "/images/lqip/aaron-lqip.jpg",
    src: "/images/aaron.png",
    alt: "A A Ron",
    href: "https://www.instagram.com/aaronhorowitz_?igsh=MWQ1ZGUxMzBkMA==",
    name: "A A Ron",
  },
  {
    id: 8,
    lqip: "/images/lqip/peaches-lqip.jpg",
    src: "/images/peaches.png",
    alt: "peaches",
    href: "https://www.instagram.com/ppeaches_10/",
    name: "peaches",
  },
  {
    id: 9,
    lqip: "/images/lqip/jenny-lqip.jpg",
    src: "/images/jenny.png",
    alt: "jenny",
    href: "https://www.instagram.com/jenn_n_juuuice/",
    name: "jenny",
  },
  {
    id: 10,
    lqip: "/images/lqip/alexjiu-lqip.jpg",
    src: "/images/alexjiu.png",
    alt: "alexj",
    href: "https://www.instagram.com/alx_jiu/",
    name: "alex jiu",
  },
  {
    id: 11,
    lqip: "/images/lqip/josh-lqip.jpg",
    src: "/images/josh.png",
    alt: "josh",
    href: "https://www.instagram.com/jamieson1832/",
    name: "josh",
  },
  {
    id: 12,
    lqip: "/images/lqip/tobi-lqip.jpg",
    src: "/images/tobi.png",
    alt: "tobi",
    href: "https://www.instagram.com/tobi_thedood/",
    name: "tobi",
  },
  {
    id: 13,
    lqip: "/images/lqip/dylan-lqip.jpg",
    src: "/images/dylan.png",
    alt: "dylan",
    href: "https://www.instagram.com/_dcooper/",
    name: "dylan",
  },
  {
    id: 14,
    lqip: "/images/lqip/taylor-lqip.jpg",
    src: "/images/taylor.png",
    alt: "taylor",
    href: "https://www.instagram.com/taygainn/",
    name: "taylor",
  },
  {
    id: 15,
    lqip: "/images/lqip/mimi-lqip.jpg",
    src: "/images/mimi.png",
    alt: "mimi",
    href: "https://www.instagram.com/chottominute/",
    name: "mimi",
  },
  {
    id: 16,
    lqip: "/images/lqip/darany-lqip.jpg",
    src: "/images/darany.png",
    alt: "darany",
    href: "https://www.instagram.com/daranylong/",
    name: "darany",
  },
  {
    id: 17,
    lqip: "/images/lqip/sunny-lqip.jpg",
    src: "/images/sunny.png",
    alt: "sunny",
    href: "https://www.instagram.com/unar_yunns?igsh=MTExbHRyemlsOWxycA==",
    name: "sunny",
  },
  {
    id: 18,
    lqip: "/images/lqip/jane-lqip.jpg",
    src: "/images/jane.png",
    alt: "jane",
    href: "https://www.instagram.com/jahnelee/",
    name: "jane",
  },
  {
    id: 19,
    lqip: "/images/lqip/cooper-lqip.jpg",
    src: "/images/cooper.png",
    alt: "cooper",
    href: "https://www.instagram.com/coopertuch/",
    name: "cooper",
  },
  {
    id: 20,
    lqip: "/images/lqip/james-lqip.jpg",
    src: "/images/james.png",
    alt: "james",
    href: "https://www.instagram.com/jlpeng/",
    name: "james",
  },
  {
    id: 21,
    lqip: "/images/lqip/vee-lqip.jpg",
    src: "/images/vee.png",
    alt: "vee",
    href: "https://www.instagram.com/veelee_x/",
    name: "vee",
  },
  {
    id: 22,
    lqip: "/images/lqip/takashi-lqip.jpg",
    src: "/images/takashi.png",
    alt: "takashi",
    href: "https://www.instagram.com/takhuynh/",
    name: "takashi",
  },
  {
    id: 23,
    lqip: "/images/lqip/ryudo-lqip.jpg",
    src: "/images/ryudo.png",
    alt: "ryudo",
    href: "https://www.instagram.com/ryudohirayamaa/",
    name: "ryudo",
  },
  {
    id: 24,
    lqip: "/images/lqip/yungjimmy-lqip.jpg",
    src: "/images/yungjimmy.png",
    alt: "yungjimmy",
    href: "https://www.instagram.com/jamesash20/",
    name: "yungjimmy",
  },
  {
    id: 25,
    lqip: "/images/lqip/parth-lqip.jpg",
    src: "/images/parth.png",
    alt: "parth",
    href: "https://www.instagram.com/p_chok/",
    name: "parth",
  },
  {
    id: 26,
    lqip: "/images/lqip/joe-lqip.jpg",
    src: "/images/joe.png",
    alt: "joe",
    href: "https://www.instagram.com/josephchung/",
    name: "joe",
  },
  {
    id: 27,
    lqip: "/images/lqip/tyler-lqip.jpg",
    src: "/images/tyler.png",
    alt: "tyler",
    href: "https://www.instagram.com/ty_workout2/",
    name: "tyler",
  },
  {
    id: 28,
    lqip: "/images/lqip/tom-lqip.jpg",
    src: "/images/tom.png",
    alt: "tom",
    href: "https://www.instagram.com/_tompham/",
    name: "tom",
  },
  {
    id: 29,
    lqip: "/images/lqip/nish-lqip.jpg",
    src: "/images/nish.png",
    alt: "nish",
    href: "https://www.instagram.com/nishfoswish/",
    name: "nish",
  },
  {
    id: 30,
    lqip: "/images/lqip/malia-lqip.jpg",
    src: "/images/malia.png",
    alt: "malia",
    href: "https://www.instagram.com/m_x_a/",
    name: "malia",
  },
  {
    id: 31,
    lqip: "/images/lqip/moodeng-lqip.jpg",
    src: "/images/moodeng.png",
    alt: "moodeng",
    href: "https://www.instagram.com/khaokheow.zoo/",
    name: "moodeng",
  },
  {
    id: 32,
    lqip: "/images/lqip/amy-lqip.jpg",
    src: "/images/amy.png",
    alt: "amy",
    href: "https://www.instagram.com/_amytp/",
    name: "amy",
  },
  {
    id: 33,
    lqip: "/images/lqip/haley-lqip.jpg",
    src: "/images/haley.png",
    alt: "haley",
    href: "https://www.instagram.com/haleydrexler/",
    name: "haley",
  },
  {
    id: 34,
    lqip: "/images/lqip/pilar-lqip.jpg",
    src: "/images/pilar.png",
    alt: "pilar",
    href: "https://www.instagram.com/dr.dmusic/",
    name: "pilar",
  },
];