export const images = [
  {
    id: 1,
    lqip: "/images/lqip/andre-lqip.jpg",
    src: "/images/andre.png",
    alt: "andre",
    href: "https://www.instagram.com/dre_yonce/",
    name: "andre",
  },
  {
    id: 2,
    lqip: "/images/lqip/adrienne-lqip.jpg",
    src: "/images/adrienne.png",
    alt: "adrienne",
    href: "https://www.instagram.com/adrienney/",
    name: "adrienne",
  },
  {
    id: 3,
    lqip: "/images/lqip/alex-lqip.jpg",
    src: "/images/alex.png",
    alt: "alex",
    href: "https://www.instagram.com/meowchow/",
    name: "alex",
  },
  {
    id: 4,
    lqip: "/images/lqip/kyoung-lqip.jpg",
    src: "/images/kyoung.png",
    alt: "kyoung",
    href: "https://www.instagram.com/k_young32/",
    name: "kyoung",
  },
  {
    id: 5,
    lqip: "/images/lqip/phil-lqip.jpg",
    src: "/images/phil.png",
    alt: "phil",
    href: "https://www.instagram.com/phillybonbilly/",
    name: "phil",
  },
  {
    id: 6,
    lqip: "/images/lqip/tran-lqip.jpg",
    src: "/images/tran.png",
    alt: "tran",
    href: "https://www.instagram.com/trantnguyen/",
    name: "tran",
  },
  {
    id: 7,
    lqip: "/images/lqip/ham-lqip.jpg",
    src: "/images/ham.png",
    alt: "hammy",
    href: "https://www.instagram.com/hamptonandeggs/",
    name: "ham",
  },
  {
    id: 8,
    lqip: "/images/lqip/peaches-lqip.jpg",
    src: "/images/peaches.png",
    alt: "peaches",
    href: "https://www.instagram.com/ppeaches_10/",
    name: 'peaches',
  },
  {
    id: 9,
    lqip: "/images/lqip/fisher-lqip.jpg",
    src: "/images/fisher.png",
    alt: "fisher",
    href: "https://www.instagram.com/followthefishtv/",
    name: 'fisher',
  },
];

